#! /usr/bin/perl -w
use 5.010;
use strict;

sub compile{
	for(@_){
		my $cmd = "erlc ./handlers/$_.erl";
		say "compiling $_.erl";
		system $cmd;
		die if $?;
	}
}

# Start here>
system "erlc funs.erl";
die if $?;

compile qw/world dir/;
#exit 0 if $#ARGV != 0;

#my $l = $ARGV[0];
#system "erlc ${l}svr.erl";
#die if $?;

for my$l("w","d"){
	system "erlc ${l}svr.erl";
	die if $?;
}

#
#say "RUNING SERVER  ...";
#system "erl -pa proto -noshell -s ${l}svr start -s init stop";

# Before the introduction to gen_server,
# we use standalone wsvr and dsvr test.
# But since wsvr and dsvr interact with sup_server
# We need to altar our test method.

system "erl -pa proto -s sup_server start_link";
die if $?;



