#! /usr/bin/perl -w
use 5.018;
use strict;

sub compile{
	for(@_){
		my $cmd = "erlc ./handlers/$_.erl";
		say "compiling $_.erl";
		system $cmd;
		die if $?;
	}
}

# Start here>
system "erlc funs.erl";
die if $?;

compile qw/world dir/;
exit 0 if $#ARGV != 0;

my $l = $ARGV[0];
system "erlc ${l}svr.erl";
die if $?;

say "RUNING SERVER  ...";
system "erl -pa proto -noshell -s ${l}svr start -s init stop";

